name: .NET Core API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    # =========================
    # RESTORE
    # =========================
    - name: Restore dependencies
      run: dotnet restore MyApi/MyApi.csproj

    # =========================
    # BUILD
    # =========================
    - name: Build project
      run: dotnet build MyApi/MyApi.csproj -c Release --no-restore

    # =========================
    # TEST (only if you have tests)
    # If no tests exist, this step can be removed
    # =========================
    - name: Run tests
      run: dotnet test MyApi/MyApi.csproj --no-build --verbosity normal
      continue-on-error: true

    # =========================
    # PUBLISH
    # =========================
    - name: Publish
      run: dotnet publish MyApi/MyApi.csproj -c Release -o ./publish --no-build

    # =========================
    # ARTIFACTS
    # =========================
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-build
        path: ./publish
